sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-guangzhou.aliyuncs.com
    access-key-id: LTAI5tGsj8dk9fNQMQfdEgpW
    access-key-secret: we0NehUsfpBMFlrmOI3Up0j1vdVRsx
    bucket-name: sky-albert
  redis:
    host: localhost
    port: 6379
    database: 0
  wechat:
    appid: wx0a8a23788547afaa
    secret: 483310875f20b28f56504dd063d9609f
    mchid:
    mchSerialNo:
    privateKeyFilePath:
    apiV3Key:
    weChatPayCertFilePath:
    notifyUrl:
    refundNotifyUrl: